/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvmDll */

#ifndef _Included_jvmDll
#define _Included_jvmDll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jvmDll
 * Method:    reloadClass
 * Signature: (Ljava/lang/Class;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_jvmDll_reloadClass__Ljava_lang_Class_2_3B
  (JNIEnv *, jclass, jclass, jbyteArray);

/*
 * Class:     jvmDll
 * Method:    reloadClass
 * Signature: ([Ljava/lang/Class;[[B)Z
 */
JNIEXPORT jboolean JNICALL Java_jvmDll_reloadClass___3Ljava_lang_Class_2_3_3B
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif